project/config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :sections
  resources :professors
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :professor
  belongs_to :section
end

project/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:assignname, :duedate, :professor_id, :section_id)
    end
end

project/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

project/app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% assignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :assigname %>
    <%= form.text_field :assignname %>
  </div>

  <div class="field">
    <%= form.label :duedate %>
    <%= form.datetime_select :duedate %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.collection_select :professor_id, Professor.all, :id, :firstname %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.collection_select :section_id, Section.all, :id, :sectionname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

project/app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignments</h1>

<table style= "width:100%">
  <thead>
    <tr>
      <th>Assignment Name</th>
      <th>Due Date</th>
      <th>Professor</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.assignname %></td>
        <td><%= assignment.duedate %></td>
        <td><%= assignment.professor.firstname %></td>
        <td><%= assignment.section.sectionname %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

project/app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

project/app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assignment Name:</strong>
  <%= @assignment.assignname %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @assignment.duedate %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @assignment.professor.firstname %>
</p>

<p>
  <strong>Section:</strong>
  <%= @assignment.section.sectionname %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>