project/config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :sections
  resources :professors
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/section.rb
class Section < ApplicationRecord
end

project/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:sectionname, :sectiontime, :sectionlocation)
    end
end

project/app/helpers/sections_helper.rb
module SectionsHelper
end

project/app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sectionname %>
    <%= form.text_field :sectionname %>
  </div>

  <div class="field">
    <%= form.label :sectiontime %>
    <%= form.datetime_select :sectiontime %>
  </div>

  <div class="field">
    <%= form.label :sectionlocation %>
    <%= form.text_field :sectionlocation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

project/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Sectionname</th>
      <th>Sectiontime</th>
      <th>Sectionlocation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.sectionname %></td>
        <td><%= section.sectiontime %></td>
        <td><%= section.sectionlocation %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

project/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

project/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sectionname:</strong>
  <%= @section.sectionname %>
</p>

<p>
  <strong>Sectiontime:</strong>
  <%= @section.sectiontime %>
</p>

<p>
  <strong>Sectionlocation:</strong>
  <%= @section.sectionlocation %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>